[package]
name = "weather_rs"
version = "0.1.0"
authors = ["Alice"]

[dependencies]
hyper ="0.12"
getopts ="0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term = "0.4.6"
chrono="0.4"
url = "1.7.2"
